export enum LocationType {
  GameLayout = 1,
  WhiteSalamanderStack,
  BlackSalamanderStack,
  VenerationPointsLayout,
  GroveStack,
  FieldStack,
  FieldSpace,
  FieldApprenticeSpace,
  SpellBookSpace,
  SecondaryDivinitiesLayout,
  BearDivinityStack,
  EagleDivinityStack,
  CristalTokenStock,
  ScrollTokenStock,
  PlayerMatLayout,
  PlayerDruidSpace,
  PlayerApprenticesSpace,
  PlayerActualRoundApprenticesSpace,
  PlayerCrystalTokenStock,
  Score100MarkerIdlePlace,
  ScorePiste
}
